import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { materializeBuiltinRelease } from "../packages/demo-games/src/authoring";
import type { BuiltinReleaseBuilder } from "../packages/demo-games/src/authoring";

function generatedSource(value: unknown): string {
  return `// Generated by bun run build:builtins. Do not edit; publish changes as a new release.\nexport default ${JSON.stringify(value, null, 2)} as const;\n`;
}

const gamesRoot = new URL("../packages/demo-games/src/games/", import.meta.url);
const buildFiles: string[] = [];
for await (const buildFile of new Bun.Glob("*/build.ts").scan({
  cwd: fileURLToPath(gamesRoot),
  onlyFiles: true,
})) buildFiles.push(buildFile);

for (const buildFile of buildFiles.sort()) {
  const module = await import(new URL(buildFile.replaceAll("\\", "/"), gamesRoot).href) as {
    BUILTIN_RELEASE_BUILDER?: BuiltinReleaseBuilder;
  };
  const builder = module.BUILTIN_RELEASE_BUILDER;
  if (builder === undefined) throw new Error(`${buildFile} does not export BUILTIN_RELEASE_BUILDER`);
  const release = materializeBuiltinRelease(builder.build());
  const url = new URL(
    `../packages/demo-games/src/games/${builder.slug}/release-${builder.releaseNumber}.generated.ts`,
    import.meta.url,
  );
  const path = fileURLToPath(url);
  const next = generatedSource(release);
  if (existsSync(path)) {
    const committed = await readFile(path, "utf8");
    if (committed !== next) {
      throw new Error(
        `${builder.slug} release ${builder.releaseNumber} is immutable; restore its builder or create release ${builder.releaseNumber + 1}`,
      );
    }
  } else {
    await writeFile(path, next, "utf8");
    console.log(`generated ${path}`);
  }
}
